### PR TITLE
add setup for python-packaging

### PR DESCRIPTION
**Pull request by makefu**
This PR adds support for python packaging (and pip releasing).

# test it
After installing [nur](https://github.com/nix-community/NUR/):
```
nix-shell -p pkgs.nur.repos.makefu.nixpkgs-pytools  --run "python-package-init docopt"
```
The derivation can be found at: https://git.shackspace.de/krebs/stockholm/blob/master/makefu/5pkgs/nixpkgs-pytools/default.nix

### CODE REVIEW

**Comment by costrouc** [comment]
This looks great. I like the use of console_scripts to expose the scripts. Also looks like I need to checkout NUR right now. I will be adding tests this week that will try out getting the information on several projects etc.

**Comment by makefu** [comment]
for testing you can of course also just fetch the build description and run it:
```
wget https://git.shackspace.de/krebs/stockholm/raw/master/makefu/5pkgs/nixpkgs-pytools/default.nix
$(nix-build -E 'with import <nixpkgs> {};pkgs.python3.pkgs.callPackage ./default.nix {}' )/bin/python-package-init
```

**Comment by makefu** [comment]
@costrouc if you think this change is fine,i'd like to merge it into master. Next step would be inclusion into nixpkgs.

**Review by costrouc — APPROVED** [review]

**Comment by costrouc** [comment]
Yes looks great with me!

**Comment by costrouc** [comment]
I will add it to nixpkgs

**Pull request merged**
